import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { marginParameters, halfMarginParameters } from '../displayParameters/marginParameters';
import { flexDirection } from '../displayParameters/flexParameters';


export default function AboutPage() {
    return (
        <>
            <Head>
                <title>Обо мне</title>
            </Head>
            <Box
                className='about-page'
                m={marginParameters}
                mt={halfMarginParameters}
                mb={halfMarginParameters}
            >
                about
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ante metus dictum at tempor commodo ullamcorper a. Aliquet lectus proin nibh nisl condimentum id. Diam maecenas ultricies mi eget mauris. Et netus et malesuada fames ac turpis. Duis convallis convallis tellus id interdum velit laoreet. Aliquam id diam maecenas ultricies mi. Elit ullamcorper dignissim cras tincidunt. Bibendum est ultricies integer quis auctor elit. In est ante in nibh mauris. Ante in nibh mauris cursus mattis molestie a iaculis. Lacus laoreet non curabitur gravida arcu ac. Lacus vestibulum sed arcu non odio euismod. Duis ultricies lacus sed turpis tincidunt.

                Cursus sit amet dictum sit amet justo. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Nec ullamcorper sit amet risus. Fames ac turpis egestas sed tempus urna et pharetra. In hac habitasse platea dictumst vestibulum rhoncus est. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Gravida neque convallis a cras semper auctor. Diam sollicitudin tempor id eu nisl. Platea dictumst quisque sagittis purus sit. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Egestas congue quisque egestas diam.

                Sit amet risus nullam eget felis eget. Arcu cursus vitae congue mauris rhoncus. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nec nam aliquam sem et tortor consequat id. Ultrices eros in cursus turpis massa tincidunt. Lacus sed turpis tincidunt id aliquet risus feugiat. Sem fringilla ut morbi tincidunt augue. Felis imperdiet proin fermentum leo vel orci porta. Netus et malesuada fames ac turpis egestas maecenas pharetra. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Molestie nunc non blandit massa enim. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Id donec ultrices tincidunt arcu non sodales. Dictum at tempor commodo ullamcorper a. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Curabitur vitae nunc sed velit dignissim sodales ut eu. Blandit turpis cursus in hac habitasse platea dictumst quisque.

                Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Lorem dolor sed viverra ipsum nunc aliquet. Suspendisse sed nisi lacus sed viverra tellus in. Risus pretium quam vulputate dignissim suspendisse in est. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Sed odio morbi quis commodo odio. Convallis convallis tellus id interdum velit laoreet. Amet cursus sit amet dictum sit amet justo donec enim. Eu lobortis elementum nibh tellus. Scelerisque in dictum non consectetur a erat nam at. Aenean et tortor at risus. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Blandit libero volutpat sed cras ornare arcu dui. Leo vel fringilla est ullamcorper. Leo vel fringilla est ullamcorper eget nulla facilisi.

                Nulla facilisi nullam vehicula ipsum. Feugiat nisl pretium fusce id velit ut. Donec adipiscing tristique risus nec feugiat. Etiam tempor orci eu lobortis elementum. Porttitor eget dolor morbi non arcu risus quis varius quam. Duis at consectetur lorem donec massa sapien faucibus et. Sit amet venenatis urna cursus eget nunc. Eget felis eget nunc lobortis mattis aliquam. Dignissim sodales ut eu sem integer vitae. Curabitur gravida arcu ac tortor dignissim convallis. Nunc sed augue lacus viverra vitae congue eu consequat ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Quis risus sed vulputate odio ut enim blandit volutpat. Viverra tellus in hac habitasse platea. Libero nunc consequat interdum varius sit amet. In hac habitasse platea dictumst vestibulum rhoncus est. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ante metus dictum at tempor commodo ullamcorper a. Aliquet lectus proin nibh nisl condimentum id. Diam maecenas ultricies mi eget mauris. Et netus et malesuada fames ac turpis. Duis convallis convallis tellus id interdum velit laoreet. Aliquam id diam maecenas ultricies mi. Elit ullamcorper dignissim cras tincidunt. Bibendum est ultricies integer quis auctor elit. In est ante in nibh mauris. Ante in nibh mauris cursus mattis molestie a iaculis. Lacus laoreet non curabitur gravida arcu ac. Lacus vestibulum sed arcu non odio euismod. Duis ultricies lacus sed turpis tincidunt.

                Cursus sit amet dictum sit amet justo. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Nec ullamcorper sit amet risus. Fames ac turpis egestas sed tempus urna et pharetra. In hac habitasse platea dictumst vestibulum rhoncus est. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Gravida neque convallis a cras semper auctor. Diam sollicitudin tempor id eu nisl. Platea dictumst quisque sagittis purus sit. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Egestas congue quisque egestas diam.

                Sit amet risus nullam eget felis eget. Arcu cursus vitae congue mauris rhoncus. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nec nam aliquam sem et tortor consequat id. Ultrices eros in cursus turpis massa tincidunt. Lacus sed turpis tincidunt id aliquet risus feugiat. Sem fringilla ut morbi tincidunt augue. Felis imperdiet proin fermentum leo vel orci porta. Netus et malesuada fames ac turpis egestas maecenas pharetra. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Molestie nunc non blandit massa enim. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Id donec ultrices tincidunt arcu non sodales. Dictum at tempor commodo ullamcorper a. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Curabitur vitae nunc sed velit dignissim sodales ut eu. Blandit turpis cursus in hac habitasse platea dictumst quisque.

                Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Lorem dolor sed viverra ipsum nunc aliquet. Suspendisse sed nisi lacus sed viverra tellus in. Risus pretium quam vulputate dignissim suspendisse in est. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Sed odio morbi quis commodo odio. Convallis convallis tellus id interdum velit laoreet. Amet cursus sit amet dictum sit amet justo donec enim. Eu lobortis elementum nibh tellus. Scelerisque in dictum non consectetur a erat nam at. Aenean et tortor at risus. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Blandit libero volutpat sed cras ornare arcu dui. Leo vel fringilla est ullamcorper. Leo vel fringilla est ullamcorper eget nulla facilisi.

                Nulla facilisi nullam vehicula ipsum. Feugiat nisl pretium fusce id velit ut. Donec adipiscing tristique risus nec feugiat. Etiam tempor orci eu lobortis elementum. Porttitor eget dolor morbi non arcu risus quis varius quam. Duis at consectetur lorem donec massa sapien faucibus et. Sit amet venenatis urna cursus eget nunc. Eget felis eget nunc lobortis mattis aliquam. Dignissim sodales ut eu sem integer vitae. Curabitur gravida arcu ac tortor dignissim convallis. Nunc sed augue lacus viverra vitae congue eu consequat ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Quis risus sed vulputate odio ut enim blandit volutpat. Viverra tellus in hac habitasse platea. Libero nunc consequat interdum varius sit amet. In hac habitasse platea dictumst vestibulum rhoncus est. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci.

                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ante metus dictum at tempor commodo ullamcorper a. Aliquet lectus proin nibh nisl condimentum id. Diam maecenas ultricies mi eget mauris. Et netus et malesuada fames ac turpis. Duis convallis convallis tellus id interdum velit laoreet. Aliquam id diam maecenas ultricies mi. Elit ullamcorper dignissim cras tincidunt. Bibendum est ultricies integer quis auctor elit. In est ante in nibh mauris. Ante in nibh mauris cursus mattis molestie a iaculis. Lacus laoreet non curabitur gravida arcu ac. Lacus vestibulum sed arcu non odio euismod. Duis ultricies lacus sed turpis tincidunt.

                Cursus sit amet dictum sit amet justo. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Nec ullamcorper sit amet risus. Fames ac turpis egestas sed tempus urna et pharetra. In hac habitasse platea dictumst vestibulum rhoncus est. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Gravida neque convallis a cras semper auctor. Diam sollicitudin tempor id eu nisl. Platea dictumst quisque sagittis purus sit. Tempus imperdiet nulla malesuada pellentesque elit eget gravida. Egestas congue quisque egestas diam.

                Sit amet risus nullam eget felis eget. Arcu cursus vitae congue mauris rhoncus. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Nec nam aliquam sem et tortor consequat id. Ultrices eros in cursus turpis massa tincidunt. Lacus sed turpis tincidunt id aliquet risus feugiat. Sem fringilla ut morbi tincidunt augue. Felis imperdiet proin fermentum leo vel orci porta. Netus et malesuada fames ac turpis egestas maecenas pharetra. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Molestie nunc non blandit massa enim. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Id donec ultrices tincidunt arcu non sodales. Dictum at tempor commodo ullamcorper a. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Curabitur vitae nunc sed velit dignissim sodales ut eu. Blandit turpis cursus in hac habitasse platea dictumst quisque.

                Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Lorem dolor sed viverra ipsum nunc aliquet. Suspendisse sed nisi lacus sed viverra tellus in. Risus pretium quam vulputate dignissim suspendisse in est. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Sed odio morbi quis commodo odio. Convallis convallis tellus id interdum velit laoreet. Amet cursus sit amet dictum sit amet justo donec enim. Eu lobortis elementum nibh tellus. Scelerisque in dictum non consectetur a erat nam at. Aenean et tortor at risus. Semper quis lectus nulla at volutpat diam ut venenatis tellus. Blandit libero volutpat sed cras ornare arcu dui. Leo vel fringilla est ullamcorper. Leo vel fringilla est ullamcorper eget nulla facilisi.

                Nulla facilisi nullam vehicula ipsum. Feugiat nisl pretium fusce id velit ut. Donec adipiscing tristique risus nec feugiat. Etiam tempor orci eu lobortis elementum. Porttitor eget dolor morbi non arcu risus quis varius quam. Duis at consectetur lorem donec massa sapien faucibus et. Sit amet venenatis urna cursus eget nunc. Eget felis eget nunc lobortis mattis aliquam. Dignissim sodales ut eu sem integer vitae. Curabitur gravida arcu ac tortor dignissim convallis. Nunc sed augue lacus viverra vitae congue eu consequat ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Quis risus sed vulputate odio ut enim blandit volutpat. Viverra tellus in hac habitasse platea. Libero nunc consequat interdum varius sit amet. In hac habitasse platea dictumst vestibulum rhoncus est. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci.
            </Box>
        </>
    )
}
